using Flue.Core.Abstractions;
using Flue.Core.Models;
using Flue.Core.Utilities;
using Flue.Infrastructure.Configuration;

namespace Flue.Infrastructure.Routing;

public sealed class FlutterRouterGenerator (
    FluePaths paths,
    IVueRouterParser routerParser) : IFlueRouterGenerator
{
    public bool IsRouterFile (string path)
    {
        return routerParser.IsRouterFile(path);
    }

    public async Task SyncAsync (CancellationToken cancellationToken = default)
    {
        var manifest = await routerParser.ParseAsync(cancellationToken);
        if (manifest is null || manifest.Routes.Length == 0)
        {
            return;
        }

        var routes = manifest.Routes
            .Where(route => route.ComponentSourceFilePath.StartsWith(paths.SourceRoot, StringComparison.OrdinalIgnoreCase))
            .Where(route => File.Exists(route.ComponentSourceFilePath))
            .DistinctBy(route => route.Path)
            .ToImmutableArray();

        if (routes.Length == 0)
        {
            return;
        }

        await WriteRouterFileAsync(manifest with { Routes = routes }, cancellationToken);
        await WriteMainFileAsync(cancellationToken);
    }

    private async Task WriteRouterFileAsync (FlueRouterManifest manifest, CancellationToken cancellationToken)
    {
        var routerOutputPath = Path.Combine(paths.DartLibRoot, "flue_router.g.dart");

        var imports = manifest.Routes
            .Select(route => paths.ToRelativeSourcePath(route.ComponentSourceFilePath))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
            .ToImmutableArray();

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Flue from vue-router config.");
        sb.AppendLine("import 'package:flutter/material.dart';");
        foreach (var relativeVuePath in imports)
        {
            var dartImport = Path.ChangeExtension(relativeVuePath, ".dart")?.Replace('\\', '/');
            sb.AppendLine($"import '{dartImport}';");
        }

        sb.AppendLine();
        sb.AppendLine("class FlueAppRouter {");
        sb.AppendLine("  const FlueAppRouter._();");
        sb.AppendLine();
        sb.AppendLine($"  static const String initialRoute = '{EscapeDart(manifest.InitialRoute)}';");
        sb.AppendLine();
        sb.AppendLine("  static final Map<String, WidgetBuilder> routes = <String, WidgetBuilder>{");

        foreach (var route in manifest.Routes)
        {
            var className = DartNaming.BuildWidgetClassName(route.ComponentSourceFilePath);
            sb.AppendLine($"    '{EscapeDart(route.Path)}': (context) => const {className}(),");
        }

        sb.AppendLine("  };\n");
        sb.AppendLine("  static final Map<String, String> nameToPath = <String, String>{");
        foreach (var route in manifest.Routes.Where(route => !string.IsNullOrWhiteSpace(route.Name)))
        {
            sb.AppendLine($"    '{EscapeDart(route.Name!)}': '{EscapeDart(route.Path)}',");
        }

        sb.AppendLine("  };\n");
        sb.AppendLine("  static String? pathByName(String name) => nameToPath[name];\n");
        sb.AppendLine("  static Route<dynamic> onUnknownRoute(RouteSettings settings) {");
        sb.AppendLine("    return MaterialPageRoute<void>(");
        sb.AppendLine("      settings: settings,");
        sb.AppendLine("      builder: (context) => Scaffold(");
        sb.AppendLine("        body: Center(");
        sb.AppendLine("          child: Text('Route not found: ${settings.name ?? 'unknown'}'),");
        sb.AppendLine("        ),");
        sb.AppendLine("      ),");
        sb.AppendLine("    );");
        sb.AppendLine("  }");
        sb.AppendLine("}");

        await File.WriteAllTextAsync(routerOutputPath, sb.ToString(), cancellationToken);
    }

    private async Task WriteMainFileAsync (CancellationToken cancellationToken)
    {
        var mainPath = Path.Combine(paths.DartLibRoot, "main.dart");

        var sb = new StringBuilder();
        sb.AppendLine("import 'package:flutter/material.dart';");
        sb.AppendLine("import 'flue_router.g.dart';");
        sb.AppendLine();
        sb.AppendLine("void main() => runApp(const FlueApp());");
        sb.AppendLine();
        sb.AppendLine("class FlueApp extends StatelessWidget {");
        sb.AppendLine("  const FlueApp({super.key});");
        sb.AppendLine();
        sb.AppendLine("  @override");
        sb.AppendLine("  Widget build(BuildContext context) {");
        sb.AppendLine("    return MaterialApp(");
        sb.AppendLine("      initialRoute: FlueAppRouter.initialRoute,");
        sb.AppendLine("      routes: FlueAppRouter.routes,");
        sb.AppendLine("      onUnknownRoute: FlueAppRouter.onUnknownRoute,");
        sb.AppendLine("    );");
        sb.AppendLine("  }");
        sb.AppendLine("}");

        await File.WriteAllTextAsync(mainPath, sb.ToString(), cancellationToken);
    }

    private static string EscapeDart (string value)
    {
        return value.Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("'", "\\'", StringComparison.Ordinal);
    }
}
