using Flue.Core.Abstractions;
using Flue.Core.Models;

namespace Flue.Infrastructure.Generation;

public sealed class DartCodeGenerator (DartWidgetRenderer widgetRenderer) : IDartCodeGenerator
{
    public string Generate (string className, TemplateNode templateRoot, LogicBridgeResult logicBridgeResult, string sourceRelativePath)
    {
        var bodyWidget = widgetRenderer.RenderRoot(templateRoot, 5);
        var stateFields = BuildStateFields(logicBridgeResult.StateFields);
        var methods = BuildMethods(logicBridgeResult.Methods);

        var sb = new StringBuilder();
        sb.AppendLine("// Generated by Flue. Source: " + sourceRelativePath);
        sb.AppendLine("// ignore_for_file: prefer_single_quotes");
        if (logicBridgeResult.RequiresJsonConvert)
        {
            sb.AppendLine("import 'dart:convert';");
        }

        sb.AppendLine("import 'package:flutter/material.dart';");
        if (logicBridgeResult.RequiresHttpClient)
        {
            sb.AppendLine("import 'package:http/http.dart' as http;");
        }

        if (logicBridgeResult.RequiresRouterSupport || bodyWidget.Contains("FlueAppRouter.", StringComparison.Ordinal))
        {
            sb.AppendLine($"import '{BuildRouterImportPath(sourceRelativePath)}';");
        }

        sb.AppendLine();
        sb.AppendLine($"class {className} extends StatefulWidget {{");
        sb.AppendLine($"  const {className}({{super.key}});");
        sb.AppendLine();
        sb.AppendLine("  @override");
        sb.AppendLine($"  State<{className}> createState() => _{className}State();");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine($"class _{className}State extends State<{className}> {{");

        if (stateFields.Length > 0)
        {
            foreach (var stateField in stateFields)
            {
                sb.AppendLine($"  {stateField}");
            }

            sb.AppendLine();
        }

        if (methods.Length > 0)
        {
            foreach (var method in methods)
            {
                sb.Append(method);
                sb.AppendLine();
                sb.AppendLine();
            }
        }

        sb.AppendLine("  @override");
        sb.AppendLine("  Widget build(BuildContext context) {");
        sb.AppendLine("    return Scaffold(");
        sb.AppendLine("      body: SafeArea(");
        sb.AppendLine("        child:");
        sb.AppendLine(bodyWidget + ",");
        sb.AppendLine("      ),");
        sb.AppendLine("    );");
        sb.AppendLine("  }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static ImmutableArray<string> BuildStateFields (ImmutableArray<StateField> stateFields)
    {
        if (stateFields.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        return [.. stateFields.Select(field => $"{field.DartType} {field.Name} = {field.Initializer};")];
    }

    private static ImmutableArray<string> BuildMethods (ImmutableArray<DartMethod> methods)
    {
        if (methods.Length == 0)
        {
            return ImmutableArray<string>.Empty;
        }

        var rendered = ImmutableArray.CreateBuilder<string>(methods.Length);
        foreach (var method in methods)
        {
            var builder = new StringBuilder();
            builder.AppendLine($"  {method.ReturnType} {method.Name}({method.Parameters}){(method.IsAsync ? " async" : string.Empty)} {{");

            if (string.IsNullOrWhiteSpace(method.Body))
            {
                builder.AppendLine("    // No-op");
            }
            else
            {
                var lines = method.Body.Split(Environment.NewLine, StringSplitOptions.RemoveEmptyEntries);
                foreach (var line in lines)
                {
                    builder.AppendLine("    " + line);
                }
            }

            builder.Append("  }");
            rendered.Add(builder.ToString());
        }

        return rendered.ToImmutable();
    }

    private static string BuildRouterImportPath (string sourceRelativePath)
    {
        var dartRelativePath = (Path.ChangeExtension(sourceRelativePath, ".dart") ?? string.Empty).Replace('\\', '/');
        var depth = dartRelativePath.Count(character => character == '/');
        if (depth == 0)
        {
            return "flue_router.g.dart";
        }

        return string.Concat(string.Join("/", Enumerable.Repeat("..", depth)), "/flue_router.g.dart");
    }
}
